# Generated by Django 6.1 on 2026-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrSchemaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_data', models.JSONField(help_text='OCR schema payload stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
